# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tecnologia e Desenvolvimento - Uma Vida Estudando
email: gmantovani2005@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog para falar de tecnologia e desenvolvimento.
  Uma vida estudando e pesquisando sobre estes assuntos e acredito importante
  compartilhar com todos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gmantovani2005.github.io" # the base hostname & protocol for your site
twitter_username: gmantovani2005
github_username:  gmantovani2005

# Build settings
markdown: kramdown
